# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(362, 430)
        AdminWindow.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 281, 351))
        self.label.setStyleSheet("border: 2px solid #FFFFFF; /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: white; /* Opcional: Para diferenciar um pouco, pode remover *")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_exit = QtWidgets.QLabel(self.centralwidget)
        self.label_exit.setGeometry(QtCore.QRect(320, 30, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(6)
        self.label_exit.setFont(font)
        self.label_exit.setObjectName("label_exit")
        self.button_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_Exit.setGeometry(QtCore.QRect(320, 10, 41, 31))
        self.button_Exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Exit.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"}\n"
"")
        self.button_Exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/icon_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Exit.setIcon(icon)
        self.button_Exit.setIconSize(QtCore.QSize(20, 50))
        self.button_Exit.setObjectName("button_Exit")
        self.login_Field = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field.setGeometry(QtCore.QRect(120, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field.setFont(font)
        self.login_Field.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field.setText("")
        self.login_Field.setObjectName("login_Field")
        self.login_Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.login_Title_3.setGeometry(QtCore.QRect(90, 60, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.login_Title_3.setFont(font)
        self.login_Title_3.setStyleSheet("color: rgb(110, 182, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"                background-color: white; /* Opcional: Para diferenciar um pouco, pode remover *")
        self.login_Title_3.setObjectName("login_Title_3")
        self.login_Field_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_4.setGeometry(QtCore.QRect(120, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_4.setFont(font)
        self.login_Field_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_4.setText("")
        self.login_Field_4.setObjectName("login_Field_4")
        self.login_Field_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_2.setGeometry(QtCore.QRect(120, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_2.setFont(font)
        self.login_Field_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_2.setText("")
        self.login_Field_2.setObjectName("login_Field_2")
        self.login_Field_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_3.setGeometry(QtCore.QRect(120, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_3.setFont(font)
        self.login_Field_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_3.setText("")
        self.login_Field_3.setObjectName("login_Field_3")
        self.icon_password = QtWidgets.QLabel(self.centralwidget)
        self.icon_password.setGeometry(QtCore.QRect(70, 290, 31, 51))
        self.icon_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_password.setText("")
        self.icon_password.setPixmap(QtGui.QPixmap("ui\\../assets/icon_password.svg"))
        self.icon_password.setObjectName("icon_password")
        self.login_Field_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_5.setGeometry(QtCore.QRect(120, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_5.setFont(font)
        self.login_Field_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_5.setText("")
        self.login_Field_5.setObjectName("login_Field_5")
        self.login_Field_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_6.setGeometry(QtCore.QRect(120, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_6.setFont(font)
        self.login_Field_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_6.setText("")
        self.login_Field_6.setObjectName("login_Field_6")
        self.icon_password_2 = QtWidgets.QLabel(self.centralwidget)
        self.icon_password_2.setGeometry(QtCore.QRect(70, 290, 31, 51))
        self.icon_password_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_password_2.setText("")
        self.icon_password_2.setPixmap(QtGui.QPixmap("ui\\../assets/icon_password.svg"))
        self.icon_password_2.setObjectName("icon_password_2")
        self.login_Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.login_Title_4.setGeometry(QtCore.QRect(90, 60, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.login_Title_4.setFont(font)
        self.login_Title_4.setStyleSheet("color: rgb(110, 182, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"                background-color: white; /* Opcional: Para diferenciar um pouco, pode remover *")
        self.login_Title_4.setObjectName("login_Title_4")
        self.login_Field_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_7.setGeometry(QtCore.QRect(120, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_7.setFont(font)
        self.login_Field_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_7.setText("")
        self.login_Field_7.setObjectName("login_Field_7")
        self.login_Field_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field_8.setGeometry(QtCore.QRect(120, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field_8.setFont(font)
        self.login_Field_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field_8.setText("")
        self.login_Field_8.setObjectName("login_Field_8")
        self.icon_password_3 = QtWidgets.QLabel(self.centralwidget)
        self.icon_password_3.setGeometry(QtCore.QRect(70, 220, 31, 51))
        self.icon_password_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_password_3.setText("")
        self.icon_password_3.setPixmap(QtGui.QPixmap("ui\\../assets/email_icon.png"))
        self.icon_password_3.setObjectName("icon_password_3")
        self.icon_password_4 = QtWidgets.QLabel(self.centralwidget)
        self.icon_password_4.setGeometry(QtCore.QRect(70, 150, 31, 51))
        self.icon_password_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_password_4.setText("")
        self.icon_password_4.setPixmap(QtGui.QPixmap("ui\\../assets/surname_icon (1).png"))
        self.icon_password_4.setObjectName("icon_password_4")
        self.icon_password_5 = QtWidgets.QLabel(self.centralwidget)
        self.icon_password_5.setGeometry(QtCore.QRect(70, 90, 31, 51))
        self.icon_password_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_password_5.setText("")
        self.icon_password_5.setPixmap(QtGui.QPixmap("ui\\../assets/name_icon.png"))
        self.icon_password_5.setObjectName("icon_password_5")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(140, 350, 93, 28))
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setStyleSheet("background-color: rgb(110, 182, 63);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid  rgb(110, 182, 63);\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.register_button.setObjectName("register_button")
        self.label_exit.raise_()
        self.label.raise_()
        self.button_Exit.raise_()
        self.login_Field.raise_()
        self.login_Title_3.raise_()
        self.login_Field_4.raise_()
        self.login_Field_2.raise_()
        self.login_Field_3.raise_()
        self.icon_password.raise_()
        self.login_Field_5.raise_()
        self.login_Field_6.raise_()
        self.icon_password_2.raise_()
        self.login_Title_4.raise_()
        self.login_Field_7.raise_()
        self.login_Field_8.raise_()
        self.icon_password_3.raise_()
        self.icon_password_4.raise_()
        self.icon_password_5.raise_()
        self.register_button.raise_()
        AdminWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "MainWindow"))
        self.label_exit.setText(_translate("AdminWindow", "     SAIR"))
        self.login_Field.setPlaceholderText(_translate("AdminWindow", "       Nome"))
        self.login_Title_3.setText(_translate("AdminWindow", "Cadastre um aluno"))
        self.login_Field_4.setPlaceholderText(_translate("AdminWindow", "   Sobrenome"))
        self.login_Field_2.setPlaceholderText(_translate("AdminWindow", "       E-mail"))
        self.login_Field_3.setPlaceholderText(_translate("AdminWindow", "       Senha"))
        self.login_Field_5.setPlaceholderText(_translate("AdminWindow", "   Sobrenome"))
        self.login_Field_6.setPlaceholderText(_translate("AdminWindow", "       Nome"))
        self.login_Title_4.setText(_translate("AdminWindow", "Cadastre um aluno"))
        self.login_Field_7.setPlaceholderText(_translate("AdminWindow", "       Senha"))
        self.login_Field_8.setPlaceholderText(_translate("AdminWindow", "       E-mail"))
        self.register_button.setText(_translate("AdminWindow", "CONCLUIR"))
