# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/questions_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 565)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setWhatsThis("")
        MainWindow.setStyleSheet("background-color: rgb(205, 255, 181);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 811, 211))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 2px solid #99ff5a; /* Mesma borda dos LineEdits */\n"
"background-color: rgb(192, 255, 164);\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: lightyellow; /* Opcional: Para diferenciar um pouco, pode remover *\n"
"")
        self.label_2.setProperty("wordWrap", False)
        self.label_2.setObjectName("label_2")
        self.Alternative_A = QtWidgets.QRadioButton(self.centralwidget)
        self.Alternative_A.setGeometry(QtCore.QRect(40, 340, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Alternative_A.setFont(font)
        self.Alternative_A.setText("")
        self.Alternative_A.setObjectName("Alternative_A")
        self.Alternative_B = QtWidgets.QRadioButton(self.centralwidget)
        self.Alternative_B.setGeometry(QtCore.QRect(40, 370, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Alternative_B.setFont(font)
        self.Alternative_B.setText("")
        self.Alternative_B.setObjectName("Alternative_B")
        self.Alternative_C = QtWidgets.QRadioButton(self.centralwidget)
        self.Alternative_C.setGeometry(QtCore.QRect(40, 410, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Alternative_C.setFont(font)
        self.Alternative_C.setWhatsThis("")
        self.Alternative_C.setText("")
        self.Alternative_C.setObjectName("Alternative_C")
        self.Alternative_D = QtWidgets.QRadioButton(self.centralwidget)
        self.Alternative_D.setGeometry(QtCore.QRect(40, 460, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Alternative_D.setFont(font)
        self.Alternative_D.setText("")
        self.Alternative_D.setObjectName("Alternative_D")
        self.Alternative_E = QtWidgets.QRadioButton(self.centralwidget)
        self.Alternative_E.setGeometry(QtCore.QRect(40, 510, 16, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Alternative_E.setFont(font)
        self.Alternative_E.setText("")
        self.Alternative_E.setObjectName("Alternative_E")
        self.button_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_Exit.setGeometry(QtCore.QRect(860, 0, 21, 41))
        self.button_Exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Exit.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"}\n"
"")
        self.button_Exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/icon_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Exit.setIcon(icon)
        self.button_Exit.setIconSize(QtCore.QSize(70, 30))
        self.button_Exit.setObjectName("button_Exit")
        self.label_exit = QtWidgets.QLabel(self.centralwidget)
        self.label_exit.setGeometry(QtCore.QRect(850, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(6)
        self.label_exit.setFont(font)
        self.label_exit.setObjectName("label_exit")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(700, 260, 172, 41))
        self.commandLinkButton.setStyleSheet("border: 2px solid #99ff5a; /* Mesma borda dos LineEdits */\n"
"background-color: rgb(192, 255, 164);\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: lightyellow; /* Opcional: Para diferenciar um pouco, pode remover *\n"
"background-color: rgb(192, 255, 164);")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 330, 841, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 400, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 360, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 450, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 500, 841, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(61, 260, 141, 41))
        self.commandLinkButton_2.setStyleSheet("border: 2px solid #99ff5a; /* Mesma borda dos LineEdits */\n"
"background-color: rgb(192, 255, 164);\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: lightyellow; /* Opcional: Para diferenciar um pouco, pode remover *\n"
"background-color: rgb(192, 255, 164);\n"
"")
        icon = QtGui.QIcon.fromTheme("none")
        self.commandLinkButton_2.setIcon(icon)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.button_ConfirmAnswer = QtWidgets.QPushButton(self.centralwidget)
        self.button_ConfirmAnswer.setGeometry(QtCore.QRect(390, 267, 171, 31))
        self.button_ConfirmAnswer.setStyleSheet("border: 2px solid #99ff5a; /* Mesma borda dos LineEdits */\n"
"background-color: rgb(192, 255, 164);\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: lightyellow; /* Opcional: Para diferenciar um pouco, pode remover *\n"
"background-color: rgb(192, 255, 164);\n"
"")
        self.button_ConfirmAnswer.setObjectName("button_ConfirmAnswer")
        self.Alternative_A.raise_()
        self.Alternative_B.raise_()
        self.Alternative_C.raise_()
        self.Alternative_D.raise_()
        self.Alternative_E.raise_()
        self.label_exit.raise_()
        self.label_2.raise_()
        self.button_Exit.raise_()
        self.commandLinkButton.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.commandLinkButton_2.raise_()
        self.button_ConfirmAnswer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_exit.setText(_translate("MainWindow", "     SAIR"))
        self.commandLinkButton.setText(_translate("MainWindow", "próxima questão"))
        self.label.setText(_translate("MainWindow", " ressalta a importância de os professores incentivarem os jovens às práticas de leitura."))
        self.label_4.setText(_translate("MainWindow", "rebate a ideia de que as políticas educacionais são eficazes no combate à crise de leitura.rebate a ideia de que políticas educacionais são eficazes no combate à crise de leitura."))
        self.label_5.setText(_translate("MainWindow", "critica pesquisas tradicionais que atribuem a falta de leitura à precariedade de bibliotecas."))
        self.label_6.setText(_translate("MainWindow", "questiona a existência de uma crise de leitura com base nos dados de pesquisas acadêmicas."))
        self.label_7.setText(_translate("MainWindow", " atribui a crise da leitura à falta de incentivos e ao desinteresse dos jovens por livros de qualidade."))
        self.commandLinkButton_2.setText(_translate("MainWindow", "questão anterior"))
        self.button_ConfirmAnswer.setText(_translate("MainWindow", "confirmar alternativa"))
