# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ranking_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RankingWindow(object):
    def setupUi(self, RankingWindow):
        RankingWindow.setObjectName("RankingWindow")
        RankingWindow.resize(643, 507)
        RankingWindow.setStyleSheet("background-color: rgb(192, 255, 164);")
        self.centralwidget = QtWidgets.QWidget(RankingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_gold = QtWidgets.QLabel(self.centralwidget)
        self.label_gold.setGeometry(QtCore.QRect(260, 50, 101, 181))
        self.label_gold.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_gold.setText("")
        self.label_gold.setObjectName("label_gold")
        self.label_bronze = QtWidgets.QLabel(self.centralwidget)
        self.label_bronze.setGeometry(QtCore.QRect(80, 120, 61, 111))
        self.label_bronze.setStyleSheet("background-color: rgb(170, 85, 0);")
        self.label_bronze.setText("")
        self.label_bronze.setObjectName("label_bronze")
        self.label_silver = QtWidgets.QLabel(self.centralwidget)
        self.label_silver.setGeometry(QtCore.QRect(460, 90, 71, 141))
        self.label_silver.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.label_silver.setText("")
        self.label_silver.setObjectName("label_silver")
        self.labelName_Position5 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_Position5.setGeometry(QtCore.QRect(40, 300, 561, 41))
        self.labelName_Position5.setStyleSheet("border: 2px solid rgb(0, 113, 0); /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: rgb(255, 255, 255); /* Opcional: Para diferenciar um pouco, pode remover *")
        self.labelName_Position5.setText("")
        self.labelName_Position5.setObjectName("labelName_Position5")
        self.labelName_Position6 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_Position6.setGeometry(QtCore.QRect(40, 350, 561, 41))
        self.labelName_Position6.setStyleSheet("border: 2px solid rgb(0, 113, 0); /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: rgb(255, 255, 255); /* Opcional: Para diferenciar um pouco, pode remover *")
        self.labelName_Position6.setText("")
        self.labelName_Position6.setObjectName("labelName_Position6")
        self.labelName_Position7 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_Position7.setGeometry(QtCore.QRect(40, 400, 561, 41))
        self.labelName_Position7.setStyleSheet("border: 2px solid rgb(0, 113, 0); /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: rgb(255, 255, 255); /* Opcional: Para diferenciar um pouco, pode remover *")
        self.labelName_Position7.setText("")
        self.labelName_Position7.setObjectName("labelName_Position7")
        self.labelName_Position8 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_Position8.setGeometry(QtCore.QRect(40, 450, 561, 41))
        self.labelName_Position8.setStyleSheet("border: 2px solid rgb(0, 113, 0); /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: rgb(255, 255, 255); /* Opcional: Para diferenciar um pouco, pode remover *")
        self.labelName_Position8.setText("")
        self.labelName_Position8.setObjectName("labelName_Position8")
        self.silver_medal = QtWidgets.QLabel(self.centralwidget)
        self.silver_medal.setGeometry(QtCore.QRect(470, 80, 61, 71))
        self.silver_medal.setStyleSheet("    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"")
        self.silver_medal.setText("")
        self.silver_medal.setPixmap(QtGui.QPixmap("ui\\../assets/silver-medal (1).png"))
        self.silver_medal.setObjectName("silver_medal")
        self.bronze_medal = QtWidgets.QLabel(self.centralwidget)
        self.bronze_medal.setGeometry(QtCore.QRect(90, 120, 41, 51))
        self.bronze_medal.setStyleSheet("    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"")
        self.bronze_medal.setText("")
        self.bronze_medal.setPixmap(QtGui.QPixmap("ui\\../assets/bronze-medal (1).png"))
        self.bronze_medal.setObjectName("bronze_medal")
        self.gold_medal = QtWidgets.QLabel(self.centralwidget)
        self.gold_medal.setGeometry(QtCore.QRect(290, 40, 41, 71))
        self.gold_medal.setStyleSheet("    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"")
        self.gold_medal.setText("")
        self.gold_medal.setPixmap(QtGui.QPixmap("ui\\../assets/gold-medal (1).png"))
        self.gold_medal.setObjectName("gold_medal")
        self.labelName_position1 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_position1.setGeometry(QtCore.QRect(110, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelName_position1.setFont(font)
        self.labelName_position1.setMouseTracking(False)
        self.labelName_position1.setTabletTracking(False)
        self.labelName_position1.setStyleSheet("    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"")
        self.labelName_position1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelName_position1.setWordWrap(True)
        self.labelName_position1.setObjectName("labelName_position1")
        self.labelName_position2 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_position2.setGeometry(QtCore.QRect(340, 50, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelName_position2.setFont(font)
        self.labelName_position2.setStyleSheet("    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"")
        self.labelName_position2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelName_position2.setWordWrap(True)
        self.labelName_position2.setObjectName("labelName_position2")
        self.labelName_position3 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_position3.setGeometry(QtCore.QRect(0, 80, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelName_position3.setFont(font)
        self.labelName_position3.setStyleSheet("    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"")
        self.labelName_position3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelName_position3.setWordWrap(True)
        self.labelName_position3.setObjectName("labelName_position3")
        self.label_exit = QtWidgets.QLabel(self.centralwidget)
        self.label_exit.setGeometry(QtCore.QRect(600, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(6)
        self.label_exit.setFont(font)
        self.label_exit.setObjectName("label_exit")
        self.button_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_Exit.setGeometry(QtCore.QRect(600, 0, 41, 31))
        self.button_Exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Exit.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Remove o fundo */\n"
"    border: none; /* Remove a borda */\n"
"    padding: 0px; /* Ajuste o espaçamento interno se necessário */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Opcional: Adicione um efeito de hover se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 50); */ /* Exemplo: um leve fundo branco transparente ao passar o mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Opcional: Adicione um efeito de pressionado se desejar */\n"
"    /* background-color: rgba(255, 255, 255, 100); */ /* Exemplo: um fundo branco um pouco mais opaco ao clicar */\n"
"}\n"
"")
        self.button_Exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/icon_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Exit.setIcon(icon)
        self.button_Exit.setIconSize(QtCore.QSize(20, 50))
        self.button_Exit.setObjectName("button_Exit")
        self.label_position4 = QtWidgets.QLabel(self.centralwidget)
        self.label_position4.setGeometry(QtCore.QRect(50, 261, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_position4.setFont(font)
        self.label_position4.setStyleSheet("\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                 background-color: transparent; /* Remove o fundo */")
        self.label_position4.setObjectName("label_position4")
        self.label_position5 = QtWidgets.QLabel(self.centralwidget)
        self.label_position5.setGeometry(QtCore.QRect(40, 310, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_position5.setFont(font)
        self.label_position5.setStyleSheet("                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                 background-color: transparent; /* Remove o fundo */")
        self.label_position5.setObjectName("label_position5")
        self.label_position7_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_position7_2.setGeometry(QtCore.QRect(50, 360, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_position7_2.setFont(font)
        self.label_position7_2.setStyleSheet("                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                 background-color: transparent; /* Remove o fundo */")
        self.label_position7_2.setObjectName("label_position7_2")
        self.label_position7 = QtWidgets.QLabel(self.centralwidget)
        self.label_position7.setGeometry(QtCore.QRect(50, 410, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_position7.setFont(font)
        self.label_position7.setStyleSheet("                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                 background-color: transparent; /* Remove o fundo */")
        self.label_position7.setObjectName("label_position7")
        self.label_position8 = QtWidgets.QLabel(self.centralwidget)
        self.label_position8.setGeometry(QtCore.QRect(50, 460, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_position8.setFont(font)
        self.label_position8.setStyleSheet("                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                 background-color: transparent; /* Remove o fundo */")
        self.label_position8.setObjectName("label_position8")
        self.labelName_Position4 = QtWidgets.QLabel(self.centralwidget)
        self.labelName_Position4.setGeometry(QtCore.QRect(40, 250, 561, 41))
        self.labelName_Position4.setStyleSheet("border: 2px solid rgb(0, 113, 0); /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: rgb(255, 255, 255); /* Opcional: Para diferenciar um pouco, pode remover *")
        self.labelName_Position4.setText("")
        self.labelName_Position4.setObjectName("labelName_Position4")
        self.labelName_Position4.raise_()
        self.labelName_Position5.raise_()
        self.labelName_Position6.raise_()
        self.labelName_Position7.raise_()
        self.labelName_Position8.raise_()
        self.labelName_position1.raise_()
        self.labelName_position2.raise_()
        self.labelName_position3.raise_()
        self.label_exit.raise_()
        self.button_Exit.raise_()
        self.label_position4.raise_()
        self.label_position5.raise_()
        self.label_position7_2.raise_()
        self.label_position7.raise_()
        self.label_position8.raise_()
        self.label_gold.raise_()
        self.label_silver.raise_()
        self.label_bronze.raise_()
        self.silver_medal.raise_()
        self.bronze_medal.raise_()
        self.gold_medal.raise_()
        RankingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RankingWindow)
        QtCore.QMetaObject.connectSlotsByName(RankingWindow)

    def retranslateUi(self, RankingWindow):
        _translate = QtCore.QCoreApplication.translate
        RankingWindow.setWindowTitle(_translate("RankingWindow", "Ranking"))
        self.labelName_position1.setText(_translate("RankingWindow", "primeiro lugar"))
        self.labelName_position2.setText(_translate("RankingWindow", "segundo lugar"))
        self.labelName_position3.setText(_translate("RankingWindow", "terceiro lugar"))
        self.label_exit.setText(_translate("RankingWindow", "     SAIR"))
        self.label_position4.setText(_translate("RankingWindow", "4°"))
        self.label_position5.setText(_translate("RankingWindow", "  5°"))
        self.label_position7_2.setText(_translate("RankingWindow", "6°"))
        self.label_position7.setText(_translate("RankingWindow", "7°"))
        self.label_position8.setText(_translate("RankingWindow", "8°"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RankingWindow = QtWidgets.QMainWindow()
    ui = Ui_RankingWindow()
    ui.setupUi(RankingWindow)
    RankingWindow.show()
    sys.exit(app.exec_())
