# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 405)
        MainWindow.setStyleSheet("background-color: rgb(192, 255, 164);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_Field = QtWidgets.QLineEdit(self.centralwidget)
        self.login_Field.setGeometry(QtCore.QRect(90, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login_Field.setFont(font)
        self.login_Field.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.login_Field.setObjectName("login_Field")
        self.password_Field = QtWidgets.QLineEdit(self.centralwidget)
        self.password_Field.setGeometry(QtCore.QRect(90, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.password_Field.setFont(font)
        self.password_Field.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(110, 182, 63);\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.password_Field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_Field.setObjectName("password_Field")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setGeometry(QtCore.QRect(40, 70, 221, 251))
        self.label_background.setStyleSheet("border: 2px solid #FFFFFF; /* Mesma borda dos LineEdits */\n"
"                border-radius: 20px; /* Mesmo arredondamento */\n"
"                padding: 5px; /* Mesmo padding */\n"
"                background-color: lightyellow; /* Opcional: Para diferenciar um pouco, pode remover *")
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.login_Title = QtWidgets.QLabel(self.centralwidget)
        self.login_Title.setGeometry(QtCore.QRect(90, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.login_Title.setFont(font)
        self.login_Title.setStyleSheet("color: rgb(0, 113, 0)")
        self.login_Title.setObjectName("login_Title")
        self.icon_login = QtWidgets.QLabel(self.centralwidget)
        self.icon_login.setGeometry(QtCore.QRect(50, 120, 31, 31))
        self.icon_login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.icon_login.setText("")
        self.icon_login.setPixmap(QtGui.QPixmap("ui\\../assets/icon_login.svg"))
        self.icon_login.setObjectName("icon_login")
        self.icon_password = QtWidgets.QLabel(self.centralwidget)
        self.icon_password.setGeometry(QtCore.QRect(50, 180, 31, 51))
        self.icon_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_password.setText("")
        self.icon_password.setPixmap(QtGui.QPixmap("ui\\../assets/icon_password.svg"))
        self.icon_password.setObjectName("icon_password")
        self.label_IFPE = QtWidgets.QLabel(self.centralwidget)
        self.label_IFPE.setGeometry(QtCore.QRect(50, 320, 201, 111))
        self.label_IFPE.setText("")
        self.label_IFPE.setPixmap(QtGui.QPixmap("ui\\../assets/logo_IFPE.png"))
        self.label_IFPE.setObjectName("label_IFPE")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(147, 214, 142);\n"
"border: 2px solid  rgb(110, 182, 63);;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton.setObjectName("pushButton")
        self.label_background.raise_()
        self.login_Field.raise_()
        self.password_Field.raise_()
        self.login_Title.raise_()
        self.icon_login.raise_()
        self.icon_password.raise_()
        self.label_IFPE.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_Field.setPlaceholderText(_translate("MainWindow", "        Usuário"))
        self.password_Field.setPlaceholderText(_translate("MainWindow", "         Senha"))
        self.login_Title.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton.setText(_translate("MainWindow", "ENTRAR"))
